baseURL = "https://demo.gethugothemes.com/navigator/examplesite/"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo3.png"

# Gestion des langues : FR / EN / NL / DE
#[[Params.listeLangues]]
#code = "fr"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"

# Gestion des langues : FR / EN / NL / DE
#[Languages]

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "es-co"
title = "Imagine Company SAS"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo3.png"
menufixed = true

#footerDescription = ""
#footerServiceTitle = "Service"
#footerQuicklinkTitle = "Quicklinks"
#footerAboutTitle = "About"
#footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = false
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable = true
heading = "Conoce nuestro trabajo."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = false
btnText = "Contactanos"
btnURL = "contact/"
videoThumb = "https://i.ytimg.com/vi/ytv7IanEKrg/hqdefault.jpg" 
videoURL = "https://www.youtube.com/embed/ytv7IanEKrg"
logo1 ="images/home/logo_tecnologia.png"
enable_footer = false

# Hero Area Section st
[Languages.en.params.hero_st]
enable = true
heading = "Conoce nuestro medio de comunicación"
description = "Somos una propuesta audiovisual innovadora donde exponemos distintas escenas culturales a nivel capital como nacional; difundiendo las nuevas propuestas musicales, temas de interés, eventos y tendencias en un espacio único para el entretenimiento del público Colombiano."
button = false
btnText = "Contactanos"
btnURL = "contact/"
videoThumb = "images/stockH/16.jpg" 
videoURL = "https://www.youtube.com/embed/YaternZ03fc"
enable_footer = true





# Hero Area Section video_init
[Languages.en.params.video_init]
enable = true
videoThumb = "images/ibanner.gif"


# About 2 Section
[Languages.en.params.aboutSm]
enable = true
title = "Presentamos Star Agency"
description = "un nuevo formato en la adquisición de proveedores y servicios audiovisuales, enfocado en cubrir las necesidades de las agencias de publicidad y el desarrollo de sus campañas. Un servicio a partir de formatos predeterminados dispuestos en nuestro tarifario, los cuales buscan incrementar el nivel actual de producción audiovisual del cliente y el volumen de producción de contenidos, manteniendo precios competitivos en los desarrollos mediante la aplicación de un plan trimestral de producción, ajustado a las necesidades del cliente y sus distintas cuentas."

# Blog Section On Homepage
[Languages.en.params.blog]
enable = true
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable = true
title = "Escríbenos"
subtitle = "Estamos aquí para responder tus preguntas y ayudarte a ser lo que imaginas."
#address = "14/05, Stockhome <br> Victori Palace , United States"
phone = "(+57) 315 2403510"
videoThumb = "images/home/foto inferior.jpg"
#fax = "+61 3827 3590"
facebook = "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/"
#dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/"
#mapLatitude = "51.507351"
#mapLongitude = "-0.127758"
#mapMarker = "images/home/Foto superior.jpg"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable = true
bg = "images/home/Foto superior.jpg"
title = "IMAGINE CREDIT"
subtitle = "Presentamos a nuestros clientes una opción de financiamiento para la adquisición inmediata de cualquiera de los productos y servicios de nuestra compañía, a partir de pago en cuotas o pagos extendidos con una tasa preferencial que varía según el perfil del cliente en medida de persona jurídica o natural en un marco del 1.5% hasta el 2.78, mediante nuestro sistema de crédito en alianza estratégica con el Banco Caja Social."
btnText = "Contactanos"
bg2 = "images/portfolio/p13.jpg"


# Call to Action Section on About Page
[Languages.en.params.cta_btn]
enable = true
bg = "images/fondo_btn.jpg"










# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
#[menu]

# Navbar Menus
[[menu.nav]]
name = "stockhousen"
url = "stockhousen/"
weight = 1

[[menu.nav]]
name = "publicidadymercadeo"
url = "publicidadymercadeo/"
weight = 2

[[menu.nav]]
name = "audiovisualycomercial"
url = "audiovisualycomercial/"
weight = 3

[[menu.nav]]
name = "tecnologia"
url = "tecnologia/"
weight = 4

[[menu.nav]]
name = "medical"
url = "medical/"
weight = 5

[[menu.nav]]
name = "low"
url = "low/"
weight = 6

#[[menu.nav]]
#name = "portfolio"
#url = "portfolio/"
#weight = 7

[[menu.nav]]
name = "contact"
url = "contact/"
weight = 8





# Footer Service Menu
[[menu.service]]
name = "graphicdesign"
url = "service/"
weight = 1
[[menu.service]]
name = "webdesign"
url = "service/"
weight = 2
[[menu.service]]
name = "webdevelopment"
url = "service/"
weight = 3

# Footer Quick links Menu
[[menu.quicklink]]
name = "partners"
url = "about/"
weight = 1
[[menu.quicklink]]
name = "about"
url = "about/"
weight = 2
[[menu.quicklink]]
name = "faqs"
url = "about/"
weight = 3
[[menu.quicklink]]
name = "badges"
url = "about/"
weight = 4
